CREATE TABLE core."GameTypePorts"
(
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "GameTypeRevisionId" integer NOT NULL,
    "ContainerPort" integer NOT NULL,
    "Protocol" varchar(10) NOT NULL,
    "AdvertisedPort" boolean NOT NULL DEFAULT false,
    "Description" text NULL,
    "DisplayOrder" integer NOT NULL DEFAULT 0,
    CONSTRAINT "FK_GameTypePorts_GameTypeRevisions_GameTypeRevisionId"
        FOREIGN KEY ("GameTypeRevisionId") REFERENCES core."GameTypeRevisions" ("Id") ON DELETE CASCADE,
    CONSTRAINT "CK_GameTypePorts_Protocol"
        CHECK ("Protocol" IN ('tcp', 'udp')),
    CONSTRAINT "CK_GameTypePorts_Range"
        CHECK ("ContainerPort" >= 1 AND "ContainerPort" <= 65535)
);

CREATE INDEX "IX_GameTypePorts_GameTypeRevisionId" ON core."GameTypePorts" ("GameTypeRevisionId");
CREATE INDEX "IX_GameTypePorts_GameTypeRevisionId_AdvertisedPort" ON core."GameTypePorts" ("GameTypeRevisionId", "AdvertisedPort");
