CREATE TABLE core."GameTypeRevisions"
(
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "GameTypeId" integer NOT NULL,
    "VersionTag" varchar(100) NOT NULL,
    "ImageReference" varchar(500) NOT NULL,
    "ImageDigest" varchar(250) NULL,
    "EnableTTY" boolean NOT NULL DEFAULT false,
    "Notes" text NULL,
    "IsPublished" boolean NOT NULL DEFAULT false,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "FK_GameTypeRevisions_GameTypes_GameTypeId"
        FOREIGN KEY ("GameTypeId") REFERENCES core."GameTypes" ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX "IX_GameTypeRevisions_GameTypeId_ImageReference_VersionTag"
    ON core."GameTypeRevisions" ("GameTypeId", "ImageReference", "VersionTag");
