CREATE TABLE core."GameTypes"
(
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Key" varchar(100) NOT NULL,
    "DisplayName" varchar(200) NOT NULL,
    "Description" text NULL,
    "Type" varchar(50) NOT NULL DEFAULT 'docker',
    "ThumbnailUrl" varchar(500) NULL,
    "DocumentationUrl" varchar(500) NULL,
    "IsActive" boolean NOT NULL DEFAULT true,
    "CurrentRevisionId" integer NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX "IX_GameTypes_Key" ON core."GameTypes" ("Key");
CREATE INDEX "IX_GameTypes_IsActive" ON core."GameTypes" ("IsActive");
