CREATE TABLE core."GameServerSettings"
(
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "GameServerId" integer NOT NULL,
    "SettingKey" varchar(200) NOT NULL,
    "Value" text NULL,
    CONSTRAINT "FK_GameServerSettings_GameServers_GameServerId"
        FOREIGN KEY ("GameServerId") REFERENCES core."GameServers" ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX "IX_GameServerSettings_GameServerId_SettingKey"
    ON core."GameServerSettings" ("GameServerId", "SettingKey");
