CREATE TABLE core."GameTypeVolumes"
(
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "GameTypeRevisionId" integer NOT NULL,
    "Source" varchar(500) NOT NULL,
    "Description" text NULL,
    "DisplayOrder" integer NOT NULL DEFAULT 0,
    "Usage" varchar(100) NOT NULL,
    CONSTRAINT "FK_GameTypeVolumes_GameTypeRevisions_GameTypeRevisionId"
        FOREIGN KEY ("GameTypeRevisionId") REFERENCES core."GameTypeRevisions" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_GameTypeVolumes_GameTypeRevisionId" ON core."GameTypeVolumes" ("GameTypeRevisionId");
