CREATE TABLE core."GameServers"
(
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ServerId" varchar(100) NOT NULL,
    "Name" varchar(200) NOT NULL,
    "Description" text NULL,
    "GameTypeRevisionId" integer NOT NULL,
    "ServiceName" varchar(200) NOT NULL,
    "Status" varchar(50) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "LastDeployedAt" timestamp with time zone NULL,
    "LastSeenAt" timestamp with time zone NULL,
    "IsDeleted" boolean NOT NULL DEFAULT false,
    CONSTRAINT "FK_GameServers_GameTypeRevisions_GameTypeRevisionId"
        FOREIGN KEY ("GameTypeRevisionId") REFERENCES core."GameTypeRevisions" ("Id") ON DELETE RESTRICT
);

CREATE UNIQUE INDEX "IX_GameServers_ServerId" ON core."GameServers" ("ServerId");
CREATE INDEX "IX_GameServers_GameTypeRevisionId" ON core."GameServers" ("GameTypeRevisionId");
CREATE INDEX "IX_GameServers_IsDeleted" ON core."GameServers" ("IsDeleted");
