CREATE TABLE core."GameTypeSettingPortMappings"
(
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "GameTypeSettingMetadataId" integer NOT NULL,
    "MappingRole" integer NOT NULL DEFAULT 0,
    "RelationType" integer NOT NULL DEFAULT 0,
    "TargetContainerPort" integer NOT NULL,
    "TargetProtocol" varchar(10) NOT NULL DEFAULT 'udp',
    "CalculationValue" integer NULL,
    "IsRequired" boolean NOT NULL DEFAULT true,
    "DisplayOrder" integer NOT NULL DEFAULT 0,
    CONSTRAINT "FK_GameTypeSettingPortMappings_GameTypeSettingMetadata_GameTypeSettingMetadataId"
        FOREIGN KEY ("GameTypeSettingMetadataId") REFERENCES core."GameTypeSettingMetadata" ("Id") ON DELETE CASCADE,
    CONSTRAINT "CK_GameTypeSettingPortMappings_Role"
        CHECK ("MappingRole" IN (0, 1)),
    CONSTRAINT "CK_GameTypeSettingPortMappings_Type"
        CHECK ("RelationType" IN (0, 1, 2, 3)),
    CONSTRAINT "CK_GameTypeSettingPortMappings_Protocol"
        CHECK ("TargetProtocol" IN ('tcp', 'udp'))
);

CREATE INDEX "IX_GameTypeSettingPortMappings_GameTypeSettingMetadataId"
    ON core."GameTypeSettingPortMappings" ("GameTypeSettingMetadataId");
