CREATE TABLE core."GameTypeSettingMetadata"
(
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "GameTypeSettingDefinitionId" integer NOT NULL,
    "DataType" varchar(50) NULL,
    "Category" varchar(100) NULL,
    "IsRequired" boolean NOT NULL DEFAULT false,
    "CannotBeEmpty" boolean NOT NULL DEFAULT false,
    "Placeholder" text NULL,
    "ValidationPattern" text NULL,
    "ValidationMessage" text NULL,
    "AutoAllocatePort" boolean NOT NULL DEFAULT false,
    "ValidateRelatedPortsAvailability" boolean NOT NULL DEFAULT true,
    "AllowedValuesJson" text NULL,
    "ValueMappingsJson" text NULL,
    CONSTRAINT "FK_GameTypeSettingMetadata_GameTypeSettingDefinitions_GameTypeSettingDefinitionId"
        FOREIGN KEY ("GameTypeSettingDefinitionId") REFERENCES core."GameTypeSettingDefinitions" ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX "IX_GameTypeSettingMetadata_GameTypeSettingDefinitionId"
    ON core."GameTypeSettingMetadata" ("GameTypeSettingDefinitionId");
