CREATE TABLE core."GameTypeSettingDefinitions"
(
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "GameTypeRevisionId" integer NOT NULL,
    "SettingKey" varchar(200) NOT NULL,
    "DefaultValue" text NULL,
    "Description" text NULL,
    "DisplayOrder" integer NOT NULL DEFAULT 0,
    CONSTRAINT "FK_GameTypeSettingDefinitions_GameTypeRevisions_GameTypeRevisionId"
        FOREIGN KEY ("GameTypeRevisionId") REFERENCES core."GameTypeRevisions" ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX "IX_GameTypeSettingDefinitions_GameTypeRevisionId_SettingKey"
    ON core."GameTypeSettingDefinitions" ("GameTypeRevisionId", "SettingKey");
