CREATE TABLE core."GameTypeWebHosts"
(
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "GameTypeRevisionId" integer NOT NULL,
    "Name" varchar(200) NOT NULL,
    "Description" text NULL,
    "PathSegment" varchar(200) NULL,
    "ContainerPort" integer NULL,
    "ContainerPortVariable" varchar(200) NULL,
    "EnabledWhen" varchar(500) NULL,
    "DisplayOrder" integer NOT NULL DEFAULT 0,
    CONSTRAINT "FK_GameTypeWebHosts_GameTypeRevisions_GameTypeRevisionId"
        FOREIGN KEY ("GameTypeRevisionId") REFERENCES core."GameTypeRevisions" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_GameTypeWebHosts_GameTypeRevisionId" ON core."GameTypeWebHosts" ("GameTypeRevisionId");
